{
  Version.mag
  State.mag
  Utils.mag
  Generics.mag
  FldPad.mag
  ValFldPad.mag
  RngUPol.mag
  ValRngUPol.mag
  RngMPol.mag
  SetCart.mag
  Promotion.mag
  DefaultAssociativeArray.mag
  Factorization_new.mag
  Ramification.mag
  HomFldPadExact.mag
  common {
    Factorization_new.mag
  }
}